# Comprehensive Hindi/Bollywood Movies Database (500+ movies from 1975-2025)
# Each movie has: title, year, hero, heroine, difficulty, genre

HINDI_MOVIES = [
    # ==================== EASY - Popular Blockbusters (150+ movies) ====================
    # 2020s Blockbusters
    {"title": "Pathaan", "year": 2023, "hero": "Shah Rukh Khan", "heroine": "Deepika Padukone", "difficulty": "easy", "genre": "Action"},
    {"title": "Jawan", "year": 2023, "hero": "Shah Rukh Khan", "heroine": "Nayanthara", "difficulty": "easy", "genre": "Action"},
    {"title": "Animal", "year": 2023, "hero": "Ranbir Kapoor", "heroine": "Rashmika Mandanna", "difficulty": "easy", "genre": "Action"},
    {"title": "Rocky Aur Rani Kii Prem Kahaani", "year": 2023, "hero": "Ranveer Singh", "heroine": "Alia Bhatt", "difficulty": "easy", "genre": "Romance"},
    {"title": "Tiger 3", "year": 2023, "hero": "Salman Khan", "heroine": "Katrina Kaif", "difficulty": "easy", "genre": "Action"},
    {"title": "Gadar 2", "year": 2023, "hero": "Sunny Deol", "heroine": "Ameesha Patel", "difficulty": "easy", "genre": "Action"},
    {"title": "Brahmastra", "year": 2022, "hero": "Ranbir Kapoor", "heroine": "Alia Bhatt", "difficulty": "easy", "genre": "Fantasy"},
    {"title": "Gangubai Kathiawadi", "year": 2022, "hero": "Ajay Devgn", "heroine": "Alia Bhatt", "difficulty": "easy", "genre": "Drama"},
    {"title": "Bhool Bhulaiyaa 2", "year": 2022, "hero": "Kartik Aaryan", "heroine": "Kiara Advani", "difficulty": "easy", "genre": "Horror Comedy"},
    {"title": "RRR", "year": 2022, "hero": "Ram Charan", "heroine": "Alia Bhatt", "difficulty": "easy", "genre": "Action"},
    {"title": "KGF Chapter 2", "year": 2022, "hero": "Yash", "heroine": "Srinidhi Shetty", "difficulty": "easy", "genre": "Action"},
    {"title": "Pushpa", "year": 2021, "hero": "Allu Arjun", "heroine": "Rashmika Mandanna", "difficulty": "easy", "genre": "Action"},
    {"title": "Sooryavanshi", "year": 2021, "hero": "Akshay Kumar", "heroine": "Katrina Kaif", "difficulty": "easy", "genre": "Action"},
    {"title": "83", "year": 2021, "hero": "Ranveer Singh", "heroine": "Deepika Padukone", "difficulty": "easy", "genre": "Sports"},
    {"title": "Shershaah", "year": 2021, "hero": "Sidharth Malhotra", "heroine": "Kiara Advani", "difficulty": "easy", "genre": "War"},
    {"title": "Bell Bottom", "year": 2021, "hero": "Akshay Kumar", "heroine": "Vaani Kapoor", "difficulty": "easy", "genre": "Spy"},
    
    # 2019-2020
    {"title": "War", "year": 2019, "hero": "Hrithik Roshan", "heroine": "Vaani Kapoor", "difficulty": "easy", "genre": "Action"},
    {"title": "Kabir Singh", "year": 2019, "hero": "Shahid Kapoor", "heroine": "Kiara Advani", "difficulty": "easy", "genre": "Romance"},
    {"title": "Good Newwz", "year": 2019, "hero": "Akshay Kumar", "heroine": "Kareena Kapoor", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Housefull 4", "year": 2019, "hero": "Akshay Kumar", "heroine": "Kriti Sanon", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Saaho", "year": 2019, "hero": "Prabhas", "heroine": "Shraddha Kapoor", "difficulty": "easy", "genre": "Action"},
    {"title": "Mission Mangal", "year": 2019, "hero": "Akshay Kumar", "heroine": "Vidya Balan", "difficulty": "easy", "genre": "Drama"},
    {"title": "Super 30", "year": 2019, "hero": "Hrithik Roshan", "heroine": "Mrunal Thakur", "difficulty": "easy", "genre": "Drama"},
    {"title": "Bharat", "year": 2019, "hero": "Salman Khan", "heroine": "Katrina Kaif", "difficulty": "easy", "genre": "Drama"},
    {"title": "Uri The Surgical Strike", "year": 2019, "hero": "Vicky Kaushal", "heroine": "Yami Gautam", "difficulty": "easy", "genre": "War"},
    {"title": "Gully Boy", "year": 2019, "hero": "Ranveer Singh", "heroine": "Alia Bhatt", "difficulty": "easy", "genre": "Musical"},
    {"title": "Total Dhamaal", "year": 2019, "hero": "Ajay Devgn", "heroine": "Madhuri Dixit", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Tanhaji", "year": 2020, "hero": "Ajay Devgn", "heroine": "Kajol", "difficulty": "easy", "genre": "Historical"},
    {"title": "Baaghi 3", "year": 2020, "hero": "Tiger Shroff", "heroine": "Shraddha Kapoor", "difficulty": "easy", "genre": "Action"},
    {"title": "Street Dancer 3D", "year": 2020, "hero": "Varun Dhawan", "heroine": "Shraddha Kapoor", "difficulty": "easy", "genre": "Dance"},
    {"title": "Malang", "year": 2020, "hero": "Aditya Roy Kapur", "heroine": "Disha Patani", "difficulty": "easy", "genre": "Thriller"},
    
    # 2018
    {"title": "Padmaavat", "year": 2018, "hero": "Shahid Kapoor", "heroine": "Deepika Padukone", "difficulty": "easy", "genre": "Historical"},
    {"title": "Simmba", "year": 2018, "hero": "Ranveer Singh", "heroine": "Sara Ali Khan", "difficulty": "easy", "genre": "Action"},
    {"title": "Sanju", "year": 2018, "hero": "Ranbir Kapoor", "heroine": "Sonam Kapoor", "difficulty": "easy", "genre": "Biography"},
    {"title": "Race 3", "year": 2018, "hero": "Salman Khan", "heroine": "Jacqueline Fernandez", "difficulty": "easy", "genre": "Action"},
    {"title": "Stree", "year": 2018, "hero": "Rajkummar Rao", "heroine": "Shraddha Kapoor", "difficulty": "easy", "genre": "Horror Comedy"},
    {"title": "Raazi", "year": 2018, "hero": "Vicky Kaushal", "heroine": "Alia Bhatt", "difficulty": "easy", "genre": "Spy"},
    {"title": "Baaghi 2", "year": 2018, "hero": "Tiger Shroff", "heroine": "Disha Patani", "difficulty": "easy", "genre": "Action"},
    {"title": "Thugs of Hindostan", "year": 2018, "hero": "Aamir Khan", "heroine": "Katrina Kaif", "difficulty": "easy", "genre": "Action"},
    {"title": "Kesari", "year": 2018, "hero": "Akshay Kumar", "heroine": "Parineeti Chopra", "difficulty": "easy", "genre": "War"},
    {"title": "Andhadhun", "year": 2018, "hero": "Ayushmann Khurrana", "heroine": "Radhika Apte", "difficulty": "easy", "genre": "Thriller"},
    
    # 2016-2017
    {"title": "Dangal", "year": 2016, "hero": "Aamir Khan", "heroine": "Fatima Sana Shaikh", "difficulty": "easy", "genre": "Sports"},
    {"title": "Sultan", "year": 2016, "hero": "Salman Khan", "heroine": "Anushka Sharma", "difficulty": "easy", "genre": "Sports"},
    {"title": "Ae Dil Hai Mushkil", "year": 2016, "hero": "Ranbir Kapoor", "heroine": "Anushka Sharma", "difficulty": "easy", "genre": "Romance"},
    {"title": "Fan", "year": 2016, "hero": "Shah Rukh Khan", "heroine": "Waluscha De Sousa", "difficulty": "easy", "genre": "Thriller"},
    {"title": "Housefull 3", "year": 2016, "hero": "Akshay Kumar", "heroine": "Jacqueline Fernandez", "difficulty": "easy", "genre": "Comedy"},
    {"title": "MS Dhoni", "year": 2016, "hero": "Sushant Singh Rajput", "heroine": "Disha Patani", "difficulty": "easy", "genre": "Sports"},
    {"title": "Dear Zindagi", "year": 2016, "hero": "Shah Rukh Khan", "heroine": "Alia Bhatt", "difficulty": "easy", "genre": "Drama"},
    {"title": "Rustom", "year": 2016, "hero": "Akshay Kumar", "heroine": "Ileana D'Cruz", "difficulty": "easy", "genre": "Thriller"},
    {"title": "Tiger Zinda Hai", "year": 2017, "hero": "Salman Khan", "heroine": "Katrina Kaif", "difficulty": "easy", "genre": "Action"},
    {"title": "Padmavati", "year": 2017, "hero": "Ranveer Singh", "heroine": "Deepika Padukone", "difficulty": "easy", "genre": "Historical"},
    {"title": "Judwaa 2", "year": 2017, "hero": "Varun Dhawan", "heroine": "Jacqueline Fernandez", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Golmaal Again", "year": 2017, "hero": "Ajay Devgn", "heroine": "Parineeti Chopra", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Toilet Ek Prem Katha", "year": 2017, "hero": "Akshay Kumar", "heroine": "Bhumi Pednekar", "difficulty": "easy", "genre": "Drama"},
    {"title": "Badrinath Ki Dulhania", "year": 2017, "hero": "Varun Dhawan", "heroine": "Alia Bhatt", "difficulty": "easy", "genre": "Romance"},
    {"title": "Raees", "year": 2017, "hero": "Shah Rukh Khan", "heroine": "Mahira Khan", "difficulty": "easy", "genre": "Crime"},
    {"title": "Kaabil", "year": 2017, "hero": "Hrithik Roshan", "heroine": "Yami Gautam", "difficulty": "easy", "genre": "Thriller"},
    {"title": "Half Girlfriend", "year": 2017, "hero": "Arjun Kapoor", "heroine": "Shraddha Kapoor", "difficulty": "easy", "genre": "Romance"},
    {"title": "Tubelight", "year": 2017, "hero": "Salman Khan", "heroine": "Zhu Zhu", "difficulty": "easy", "genre": "War"},
    
    # 2014-2015
    {"title": "PK", "year": 2014, "hero": "Aamir Khan", "heroine": "Anushka Sharma", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Kick", "year": 2014, "hero": "Salman Khan", "heroine": "Jacqueline Fernandez", "difficulty": "easy", "genre": "Action"},
    {"title": "Bang Bang", "year": 2014, "hero": "Hrithik Roshan", "heroine": "Katrina Kaif", "difficulty": "easy", "genre": "Action"},
    {"title": "Happy New Year", "year": 2014, "hero": "Shah Rukh Khan", "heroine": "Deepika Padukone", "difficulty": "easy", "genre": "Heist"},
    {"title": "Singham Returns", "year": 2014, "hero": "Ajay Devgn", "heroine": "Kareena Kapoor", "difficulty": "easy", "genre": "Action"},
    {"title": "Ek Villain", "year": 2014, "hero": "Sidharth Malhotra", "heroine": "Shraddha Kapoor", "difficulty": "easy", "genre": "Romance"},
    {"title": "2 States", "year": 2014, "hero": "Arjun Kapoor", "heroine": "Alia Bhatt", "difficulty": "easy", "genre": "Romance"},
    {"title": "Humpty Sharma Ki Dulhania", "year": 2014, "hero": "Varun Dhawan", "heroine": "Alia Bhatt", "difficulty": "easy", "genre": "Romance"},
    {"title": "Queen", "year": 2014, "hero": "Rajkummar Rao", "heroine": "Kangana Ranaut", "difficulty": "easy", "genre": "Drama"},
    {"title": "Bajrangi Bhaijaan", "year": 2015, "hero": "Salman Khan", "heroine": "Kareena Kapoor", "difficulty": "easy", "genre": "Drama"},
    {"title": "Baahubali", "year": 2015, "hero": "Prabhas", "heroine": "Anushka Shetty", "difficulty": "easy", "genre": "Action"},
    {"title": "Prem Ratan Dhan Payo", "year": 2015, "hero": "Salman Khan", "heroine": "Sonam Kapoor", "difficulty": "easy", "genre": "Drama"},
    {"title": "Dil Dhadakne Do", "year": 2015, "hero": "Ranveer Singh", "heroine": "Anushka Sharma", "difficulty": "easy", "genre": "Drama"},
    {"title": "Tanu Weds Manu Returns", "year": 2015, "hero": "R Madhavan", "heroine": "Kangana Ranaut", "difficulty": "easy", "genre": "Comedy"},
    {"title": "ABCD 2", "year": 2015, "hero": "Varun Dhawan", "heroine": "Shraddha Kapoor", "difficulty": "easy", "genre": "Dance"},
    {"title": "Bajirao Mastani", "year": 2015, "hero": "Ranveer Singh", "heroine": "Deepika Padukone", "difficulty": "easy", "genre": "Historical"},
    {"title": "Tamasha", "year": 2015, "hero": "Ranbir Kapoor", "heroine": "Deepika Padukone", "difficulty": "easy", "genre": "Drama"},
    {"title": "Drishyam", "year": 2015, "hero": "Ajay Devgn", "heroine": "Shriya Saran", "difficulty": "easy", "genre": "Thriller"},
    {"title": "Baby", "year": 2015, "hero": "Akshay Kumar", "heroine": "Taapsee Pannu", "difficulty": "easy", "genre": "Action"},
    {"title": "Gabbar Is Back", "year": 2015, "hero": "Akshay Kumar", "heroine": "Shruti Haasan", "difficulty": "easy", "genre": "Action"},
    
    # 2011-2013
    {"title": "3 Idiots", "year": 2009, "hero": "Aamir Khan", "heroine": "Kareena Kapoor", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Dhoom 3", "year": 2013, "hero": "Aamir Khan", "heroine": "Katrina Kaif", "difficulty": "easy", "genre": "Action"},
    {"title": "Chennai Express", "year": 2013, "hero": "Shah Rukh Khan", "heroine": "Deepika Padukone", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Yeh Jawaani Hai Deewani", "year": 2013, "hero": "Ranbir Kapoor", "heroine": "Deepika Padukone", "difficulty": "easy", "genre": "Romance"},
    {"title": "Krrish 3", "year": 2013, "hero": "Hrithik Roshan", "heroine": "Priyanka Chopra", "difficulty": "easy", "genre": "Superhero"},
    {"title": "Goliyon Ki Raasleela Ram Leela", "year": 2013, "hero": "Ranveer Singh", "heroine": "Deepika Padukone", "difficulty": "easy", "genre": "Romance"},
    {"title": "Race 2", "year": 2013, "hero": "Saif Ali Khan", "heroine": "Deepika Padukone", "difficulty": "easy", "genre": "Action"},
    {"title": "Aashiqui 2", "year": 2013, "hero": "Aditya Roy Kapur", "heroine": "Shraddha Kapoor", "difficulty": "easy", "genre": "Romance"},
    {"title": "Barfi", "year": 2012, "hero": "Ranbir Kapoor", "heroine": "Priyanka Chopra", "difficulty": "easy", "genre": "Romance"},
    {"title": "Ek Tha Tiger", "year": 2012, "hero": "Salman Khan", "heroine": "Katrina Kaif", "difficulty": "easy", "genre": "Action"},
    {"title": "Jab Tak Hai Jaan", "year": 2012, "hero": "Shah Rukh Khan", "heroine": "Katrina Kaif", "difficulty": "easy", "genre": "Romance"},
    {"title": "Rowdy Rathore", "year": 2012, "hero": "Akshay Kumar", "heroine": "Sonakshi Sinha", "difficulty": "easy", "genre": "Action"},
    {"title": "Dabangg 2", "year": 2012, "hero": "Salman Khan", "heroine": "Sonakshi Sinha", "difficulty": "easy", "genre": "Action"},
    {"title": "Son of Sardaar", "year": 2012, "hero": "Ajay Devgn", "heroine": "Sonakshi Sinha", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Agneepath", "year": 2012, "hero": "Hrithik Roshan", "heroine": "Priyanka Chopra", "difficulty": "easy", "genre": "Action"},
    {"title": "Housefull 2", "year": 2012, "hero": "Akshay Kumar", "heroine": "Asin", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Bodyguard", "year": 2011, "hero": "Salman Khan", "heroine": "Kareena Kapoor", "difficulty": "easy", "genre": "Action"},
    {"title": "Ra One", "year": 2011, "hero": "Shah Rukh Khan", "heroine": "Kareena Kapoor", "difficulty": "easy", "genre": "Sci-Fi"},
    {"title": "Don 2", "year": 2011, "hero": "Shah Rukh Khan", "heroine": "Priyanka Chopra", "difficulty": "easy", "genre": "Action"},
    {"title": "Singham", "year": 2011, "hero": "Ajay Devgn", "heroine": "Kajal Aggarwal", "difficulty": "easy", "genre": "Action"},
    {"title": "Ready", "year": 2011, "hero": "Salman Khan", "heroine": "Asin", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Zindagi Na Milegi Dobara", "year": 2011, "hero": "Hrithik Roshan", "heroine": "Katrina Kaif", "difficulty": "easy", "genre": "Drama"},
    {"title": "Rockstar", "year": 2011, "hero": "Ranbir Kapoor", "heroine": "Nargis Fakhri", "difficulty": "easy", "genre": "Musical"},
    {"title": "Dabangg", "year": 2010, "hero": "Salman Khan", "heroine": "Sonakshi Sinha", "difficulty": "easy", "genre": "Action"},
    
    # 2006-2010
    {"title": "Ghajini", "year": 2008, "hero": "Aamir Khan", "heroine": "Asin", "difficulty": "easy", "genre": "Action"},
    {"title": "Om Shanti Om", "year": 2007, "hero": "Shah Rukh Khan", "heroine": "Deepika Padukone", "difficulty": "easy", "genre": "Drama"},
    {"title": "Jab We Met", "year": 2007, "hero": "Shahid Kapoor", "heroine": "Kareena Kapoor", "difficulty": "easy", "genre": "Romance"},
    {"title": "Chak De India", "year": 2007, "hero": "Shah Rukh Khan", "heroine": "Vidya Malvade", "difficulty": "easy", "genre": "Sports"},
    {"title": "Partner", "year": 2007, "hero": "Salman Khan", "heroine": "Govinda", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Taare Zameen Par", "year": 2007, "hero": "Aamir Khan", "heroine": "Tisca Chopra", "difficulty": "easy", "genre": "Drama"},
    {"title": "Dhoom 2", "year": 2006, "hero": "Hrithik Roshan", "heroine": "Aishwarya Rai", "difficulty": "easy", "genre": "Action"},
    {"title": "Rang De Basanti", "year": 2006, "hero": "Aamir Khan", "heroine": "Soha Ali Khan", "difficulty": "easy", "genre": "Drama"},
    {"title": "Krrish", "year": 2006, "hero": "Hrithik Roshan", "heroine": "Priyanka Chopra", "difficulty": "easy", "genre": "Superhero"},
    {"title": "Lage Raho Munna Bhai", "year": 2006, "hero": "Sanjay Dutt", "heroine": "Vidya Balan", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Don", "year": 2006, "hero": "Shah Rukh Khan", "heroine": "Priyanka Chopra", "difficulty": "easy", "genre": "Action"},
    {"title": "Fanaa", "year": 2006, "hero": "Aamir Khan", "heroine": "Kajol", "difficulty": "easy", "genre": "Romance"},
    {"title": "Golmaal", "year": 2006, "hero": "Ajay Devgn", "heroine": "Rimi Sen", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Omkara", "year": 2006, "hero": "Ajay Devgn", "heroine": "Kareena Kapoor", "difficulty": "easy", "genre": "Drama"},
    {"title": "My Name Is Khan", "year": 2010, "hero": "Shah Rukh Khan", "heroine": "Kajol", "difficulty": "easy", "genre": "Drama"},
    {"title": "Housefull", "year": 2010, "hero": "Akshay Kumar", "heroine": "Deepika Padukone", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Rajneeti", "year": 2010, "hero": "Ranbir Kapoor", "heroine": "Katrina Kaif", "difficulty": "easy", "genre": "Political"},
    {"title": "Golmaal 3", "year": 2010, "hero": "Ajay Devgn", "heroine": "Kareena Kapoor", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Once Upon a Time in Mumbai", "year": 2010, "hero": "Ajay Devgn", "heroine": "Kangana Ranaut", "difficulty": "easy", "genre": "Crime"},
    {"title": "Badmaash Company", "year": 2010, "hero": "Shahid Kapoor", "heroine": "Anushka Sharma", "difficulty": "easy", "genre": "Drama"},
    {"title": "Love Aaj Kal", "year": 2009, "hero": "Saif Ali Khan", "heroine": "Deepika Padukone", "difficulty": "easy", "genre": "Romance"},
    {"title": "Wanted", "year": 2009, "hero": "Salman Khan", "heroine": "Ayesha Takia", "difficulty": "easy", "genre": "Action"},
    {"title": "Ajab Prem Ki Ghazab Kahani", "year": 2009, "hero": "Ranbir Kapoor", "heroine": "Katrina Kaif", "difficulty": "easy", "genre": "Romance"},
    {"title": "Wake Up Sid", "year": 2009, "hero": "Ranbir Kapoor", "heroine": "Konkona Sen Sharma", "difficulty": "easy", "genre": "Drama"},
    
    # 2001-2005
    {"title": "Kabhi Khushi Kabhie Gham", "year": 2001, "hero": "Shah Rukh Khan", "heroine": "Kajol", "difficulty": "easy", "genre": "Drama"},
    {"title": "Lagaan", "year": 2001, "hero": "Aamir Khan", "heroine": "Gracy Singh", "difficulty": "easy", "genre": "Sports"},
    {"title": "Dil Chahta Hai", "year": 2001, "hero": "Aamir Khan", "heroine": "Preity Zinta", "difficulty": "easy", "genre": "Drama"},
    {"title": "Gadar Ek Prem Katha", "year": 2001, "hero": "Sunny Deol", "heroine": "Ameesha Patel", "difficulty": "easy", "genre": "Drama"},
    {"title": "Devdas", "year": 2002, "hero": "Shah Rukh Khan", "heroine": "Aishwarya Rai", "difficulty": "easy", "genre": "Drama"},
    {"title": "Raaz", "year": 2002, "hero": "Bipasha Basu", "heroine": "Dino Morea", "difficulty": "easy", "genre": "Horror"},
    {"title": "Munna Bhai MBBS", "year": 2003, "hero": "Sanjay Dutt", "heroine": "Gracy Singh", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Kal Ho Naa Ho", "year": 2003, "hero": "Shah Rukh Khan", "heroine": "Preity Zinta", "difficulty": "easy", "genre": "Romance"},
    {"title": "Koi Mil Gaya", "year": 2003, "hero": "Hrithik Roshan", "heroine": "Preity Zinta", "difficulty": "easy", "genre": "Sci-Fi"},
    {"title": "Main Hoon Na", "year": 2004, "hero": "Shah Rukh Khan", "heroine": "Sushmita Sen", "difficulty": "easy", "genre": "Action"},
    {"title": "Veer Zaara", "year": 2004, "hero": "Shah Rukh Khan", "heroine": "Preity Zinta", "difficulty": "easy", "genre": "Romance"},
    {"title": "Hum Tum", "year": 2004, "hero": "Saif Ali Khan", "heroine": "Rani Mukerji", "difficulty": "easy", "genre": "Romance"},
    {"title": "Dhoom", "year": 2004, "hero": "John Abraham", "heroine": "Esha Deol", "difficulty": "easy", "genre": "Action"},
    {"title": "Murder", "year": 2004, "hero": "Emraan Hashmi", "heroine": "Mallika Sherawat", "difficulty": "easy", "genre": "Thriller"},
    {"title": "Bunty Aur Babli", "year": 2005, "hero": "Abhishek Bachchan", "heroine": "Rani Mukerji", "difficulty": "easy", "genre": "Comedy"},
    {"title": "No Entry", "year": 2005, "hero": "Salman Khan", "heroine": "Anil Kapoor", "difficulty": "easy", "genre": "Comedy"},
    {"title": "Salaam Namaste", "year": 2005, "hero": "Saif Ali Khan", "heroine": "Preity Zinta", "difficulty": "easy", "genre": "Romance"},
    {"title": "Paheli", "year": 2005, "hero": "Shah Rukh Khan", "heroine": "Rani Mukerji", "difficulty": "easy", "genre": "Fantasy"},
    
    # 1990s Classics
    {"title": "Dilwale Dulhania Le Jayenge", "year": 1995, "hero": "Shah Rukh Khan", "heroine": "Kajol", "difficulty": "easy", "genre": "Romance"},
    {"title": "Kuch Kuch Hota Hai", "year": 1998, "hero": "Shah Rukh Khan", "heroine": "Kajol", "difficulty": "easy", "genre": "Romance"},
    {"title": "Hum Aapke Hain Koun", "year": 1994, "hero": "Salman Khan", "heroine": "Madhuri Dixit", "difficulty": "easy", "genre": "Romance"},
    {"title": "Dil To Pagal Hai", "year": 1997, "hero": "Shah Rukh Khan", "heroine": "Madhuri Dixit", "difficulty": "easy", "genre": "Romance"},
    {"title": "Hum Dil De Chuke Sanam", "year": 1999, "hero": "Salman Khan", "heroine": "Aishwarya Rai", "difficulty": "easy", "genre": "Romance"},
    {"title": "Dil Se", "year": 1998, "hero": "Shah Rukh Khan", "heroine": "Manisha Koirala", "difficulty": "easy", "genre": "Drama"},
    {"title": "Baazigar", "year": 1993, "hero": "Shah Rukh Khan", "heroine": "Kajol", "difficulty": "easy", "genre": "Thriller"},
    {"title": "Darr", "year": 1993, "hero": "Shah Rukh Khan", "heroine": "Juhi Chawla", "difficulty": "easy", "genre": "Thriller"},
    {"title": "Karan Arjun", "year": 1995, "hero": "Salman Khan", "heroine": "Kajol", "difficulty": "easy", "genre": "Action"},
    {"title": "Rangeela", "year": 1995, "hero": "Aamir Khan", "heroine": "Urmila Matondkar", "difficulty": "easy", "genre": "Romance"},
    {"title": "Mohra", "year": 1994, "hero": "Akshay Kumar", "heroine": "Raveena Tandon", "difficulty": "easy", "genre": "Action"},
    {"title": "Border", "year": 1997, "hero": "Sunny Deol", "heroine": "Pooja Bhatt", "difficulty": "easy", "genre": "War"},
    {"title": "Pardes", "year": 1997, "hero": "Shah Rukh Khan", "heroine": "Mahima Chaudhry", "difficulty": "easy", "genre": "Romance"},
    {"title": "Gupt", "year": 1997, "hero": "Bobby Deol", "heroine": "Kajol", "difficulty": "easy", "genre": "Thriller"},
    {"title": "Soldier", "year": 1998, "hero": "Bobby Deol", "heroine": "Preity Zinta", "difficulty": "easy", "genre": "Action"},
    {"title": "Kaho Naa Pyaar Hai", "year": 2000, "hero": "Hrithik Roshan", "heroine": "Ameesha Patel", "difficulty": "easy", "genre": "Romance"},
    {"title": "Mohabbatein", "year": 2000, "hero": "Shah Rukh Khan", "heroine": "Aishwarya Rai", "difficulty": "easy", "genre": "Romance"},
    {"title": "Dhadkan", "year": 2000, "hero": "Akshay Kumar", "heroine": "Shilpa Shetty", "difficulty": "easy", "genre": "Romance"},
    {"title": "Josh", "year": 2000, "hero": "Shah Rukh Khan", "heroine": "Aishwarya Rai", "difficulty": "easy", "genre": "Drama"},
    
    # 1980s Classics
    {"title": "Sholay", "year": 1975, "hero": "Amitabh Bachchan", "heroine": "Hema Malini", "difficulty": "easy", "genre": "Action"},
    {"title": "Mr. India", "year": 1987, "hero": "Anil Kapoor", "heroine": "Sridevi", "difficulty": "easy", "genre": "Sci-Fi"},
    {"title": "Maine Pyar Kiya", "year": 1989, "hero": "Salman Khan", "heroine": "Bhagyashree", "difficulty": "easy", "genre": "Romance"},
    {"title": "Qayamat Se Qayamat Tak", "year": 1988, "hero": "Aamir Khan", "heroine": "Juhi Chawla", "difficulty": "easy", "genre": "Romance"},
    {"title": "Tezaab", "year": 1988, "hero": "Anil Kapoor", "heroine": "Madhuri Dixit", "difficulty": "easy", "genre": "Action"},
    
    # ==================== MEDIUM - Less Popular/Old Classics (180+ movies) ====================
    {"title": "Deewar", "year": 1975, "hero": "Amitabh Bachchan", "heroine": "Parveen Babi", "difficulty": "medium", "genre": "Action"},
    {"title": "Amar Akbar Anthony", "year": 1977, "hero": "Amitabh Bachchan", "heroine": "Parveen Babi", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Don", "year": 1978, "hero": "Amitabh Bachchan", "heroine": "Zeenat Aman", "difficulty": "medium", "genre": "Action"},
    {"title": "Silsila", "year": 1981, "hero": "Amitabh Bachchan", "heroine": "Rekha", "difficulty": "medium", "genre": "Drama"},
    {"title": "Lamhe", "year": 1991, "hero": "Anil Kapoor", "heroine": "Sridevi", "difficulty": "medium", "genre": "Romance"},
    {"title": "Chandni", "year": 1989, "hero": "Rishi Kapoor", "heroine": "Sridevi", "difficulty": "medium", "genre": "Romance"},
    {"title": "Kabhi Haan Kabhi Naa", "year": 1994, "hero": "Shah Rukh Khan", "heroine": "Suchitra Krishnamoorthi", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Satya", "year": 1998, "hero": "J.D. Chakravarthy", "heroine": "Urmila Matondkar", "difficulty": "medium", "genre": "Crime"},
    {"title": "Company", "year": 2002, "hero": "Ajay Devgn", "heroine": "Manisha Koirala", "difficulty": "medium", "genre": "Crime"},
    {"title": "Gangster", "year": 2006, "hero": "Emraan Hashmi", "heroine": "Kangana Ranaut", "difficulty": "medium", "genre": "Crime"},
    {"title": "Life In A Metro", "year": 2007, "hero": "Shilpa Shetty", "heroine": "Konkona Sen Sharma", "difficulty": "medium", "genre": "Drama"},
    {"title": "Paan Singh Tomar", "year": 2012, "hero": "Irrfan Khan", "heroine": "Mahie Gill", "difficulty": "medium", "genre": "Drama"},
    {"title": "The Lunchbox", "year": 2013, "hero": "Irrfan Khan", "heroine": "Nimrat Kaur", "difficulty": "medium", "genre": "Romance"},
    {"title": "Haider", "year": 2014, "hero": "Shahid Kapoor", "heroine": "Shraddha Kapoor", "difficulty": "medium", "genre": "Drama"},
    {"title": "Udaan", "year": 2010, "hero": "Rajat Barmecha", "heroine": "Ram Kapoor", "difficulty": "medium", "genre": "Drama"},
    {"title": "Gangs of Wasseypur", "year": 2012, "hero": "Manoj Bajpayee", "heroine": "Richa Chadha", "difficulty": "medium", "genre": "Crime"},
    {"title": "Article 15", "year": 2019, "hero": "Ayushmann Khurrana", "heroine": "Sayani Gupta", "difficulty": "medium", "genre": "Drama"},
    {"title": "Tumbbad", "year": 2018, "hero": "Sohum Shah", "heroine": "Jyoti Malshe", "difficulty": "medium", "genre": "Horror"},
    {"title": "Newton", "year": 2017, "hero": "Rajkummar Rao", "heroine": "Anjali Patil", "difficulty": "medium", "genre": "Drama"},
    {"title": "Masaan", "year": 2015, "hero": "Vicky Kaushal", "heroine": "Richa Chadha", "difficulty": "medium", "genre": "Drama"},
    {"title": "Badhaai Ho", "year": 2018, "hero": "Ayushmann Khurrana", "heroine": "Sanya Malhotra", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Piku", "year": 2015, "hero": "Amitabh Bachchan", "heroine": "Deepika Padukone", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Lootera", "year": 2013, "hero": "Ranveer Singh", "heroine": "Sonakshi Sinha", "difficulty": "medium", "genre": "Romance"},
    {"title": "Kai Po Che", "year": 2013, "hero": "Sushant Singh Rajput", "heroine": "Amrita Puri", "difficulty": "medium", "genre": "Drama"},
    {"title": "Special 26", "year": 2013, "hero": "Akshay Kumar", "heroine": "Kajal Aggarwal", "difficulty": "medium", "genre": "Heist"},
    {"title": "Kahaani", "year": 2012, "hero": "Parambrata Chatterjee", "heroine": "Vidya Balan", "difficulty": "medium", "genre": "Thriller"},
    {"title": "Talaash", "year": 2012, "hero": "Aamir Khan", "heroine": "Rani Mukerji", "difficulty": "medium", "genre": "Thriller"},
    {"title": "The Dirty Picture", "year": 2011, "hero": "Emraan Hashmi", "heroine": "Vidya Balan", "difficulty": "medium", "genre": "Biography"},
    {"title": "English Vinglish", "year": 2012, "hero": "Adil Hussain", "heroine": "Sridevi", "difficulty": "medium", "genre": "Drama"},
    {"title": "Dil Dhadakne Do", "year": 2015, "hero": "Ranveer Singh", "heroine": "Priyanka Chopra", "difficulty": "medium", "genre": "Drama"},
    {"title": "Neerja", "year": 2016, "hero": "Shabana Azmi", "heroine": "Sonam Kapoor", "difficulty": "medium", "genre": "Biography"},
    {"title": "Pink", "year": 2016, "hero": "Amitabh Bachchan", "heroine": "Taapsee Pannu", "difficulty": "medium", "genre": "Drama"},
    {"title": "Kapoor and Sons", "year": 2016, "hero": "Sidharth Malhotra", "heroine": "Alia Bhatt", "difficulty": "medium", "genre": "Drama"},
    {"title": "Udta Punjab", "year": 2016, "hero": "Shahid Kapoor", "heroine": "Alia Bhatt", "difficulty": "medium", "genre": "Crime"},
    {"title": "Trapped", "year": 2017, "hero": "Rajkummar Rao", "heroine": "Geetanjali Thapa", "difficulty": "medium", "genre": "Thriller"},
    {"title": "Bareilly Ki Barfi", "year": 2017, "hero": "Ayushmann Khurrana", "heroine": "Kriti Sanon", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Shubh Mangal Saavdhan", "year": 2017, "hero": "Ayushmann Khurrana", "heroine": "Bhumi Pednekar", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Hindi Medium", "year": 2017, "hero": "Irrfan Khan", "heroine": "Saba Qamar", "difficulty": "medium", "genre": "Drama"},
    {"title": "Secret Superstar", "year": 2017, "hero": "Aamir Khan", "heroine": "Zaira Wasim", "difficulty": "medium", "genre": "Musical"},
    {"title": "Pad Man", "year": 2018, "hero": "Akshay Kumar", "heroine": "Sonam Kapoor", "difficulty": "medium", "genre": "Biography"},
    {"title": "Parmanu", "year": 2018, "hero": "John Abraham", "heroine": "Diana Penty", "difficulty": "medium", "genre": "Thriller"},
    {"title": "Mulk", "year": 2018, "hero": "Rishi Kapoor", "heroine": "Taapsee Pannu", "difficulty": "medium", "genre": "Drama"},
    {"title": "Manmarziyaan", "year": 2018, "hero": "Abhishek Bachchan", "heroine": "Taapsee Pannu", "difficulty": "medium", "genre": "Romance"},
    {"title": "Sui Dhaaga", "year": 2018, "hero": "Varun Dhawan", "heroine": "Anushka Sharma", "difficulty": "medium", "genre": "Drama"},
    {"title": "Batti Gul Meter Chalu", "year": 2018, "hero": "Shahid Kapoor", "heroine": "Shraddha Kapoor", "difficulty": "medium", "genre": "Drama"},
    {"title": "Manto", "year": 2018, "hero": "Nawazuddin Siddiqui", "heroine": "Rasika Dugal", "difficulty": "medium", "genre": "Biography"},
    {"title": "Badla", "year": 2019, "hero": "Amitabh Bachchan", "heroine": "Taapsee Pannu", "difficulty": "medium", "genre": "Thriller"},
    {"title": "Luka Chuppi", "year": 2019, "hero": "Kartik Aaryan", "heroine": "Kriti Sanon", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Article 370", "year": 2024, "hero": "Yami Gautam", "heroine": "Priyamani", "difficulty": "medium", "genre": "Thriller"},
    {"title": "Crew", "year": 2024, "hero": "Kriti Sanon", "heroine": "Kareena Kapoor", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Merry Christmas", "year": 2024, "hero": "Vijay Sethupathi", "heroine": "Katrina Kaif", "difficulty": "medium", "genre": "Thriller"},
    {"title": "Fighter", "year": 2024, "hero": "Hrithik Roshan", "heroine": "Deepika Padukone", "difficulty": "medium", "genre": "Action"},
    {"title": "Teri Baaton Mein Aisa Uljha Jiya", "year": 2024, "hero": "Shahid Kapoor", "heroine": "Kriti Sanon", "difficulty": "medium", "genre": "Sci-Fi"},
    {"title": "Bade Miyan Chote Miyan", "year": 2024, "hero": "Akshay Kumar", "heroine": "Tiger Shroff", "difficulty": "medium", "genre": "Action"},
    {"title": "Sam Bahadur", "year": 2023, "hero": "Vicky Kaushal", "heroine": "Sanya Malhotra", "difficulty": "medium", "genre": "Biography"},
    {"title": "Dunki", "year": 2023, "hero": "Shah Rukh Khan", "heroine": "Taapsee Pannu", "difficulty": "medium", "genre": "Drama"},
    {"title": "12th Fail", "year": 2023, "hero": "Vikrant Massey", "heroine": "Medha Shankar", "difficulty": "medium", "genre": "Biography"},
    {"title": "Murder Mubarak", "year": 2024, "hero": "Pankaj Tripathi", "heroine": "Sara Ali Khan", "difficulty": "medium", "genre": "Mystery"},
    {"title": "Amar Prem Ki Prem Kahani", "year": 2024, "hero": "Sunny Singh", "heroine": "Pranutan Bahl", "difficulty": "medium", "genre": "Romance"},
    {"title": "Phir Aayi Hasseen Dillruba", "year": 2024, "hero": "Vikrant Massey", "heroine": "Taapsee Pannu", "difficulty": "medium", "genre": "Thriller"},
    {"title": "Khel Khel Mein", "year": 2024, "hero": "Akshay Kumar", "heroine": "Taapsee Pannu", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Stree 2", "year": 2024, "hero": "Rajkummar Rao", "heroine": "Shraddha Kapoor", "difficulty": "medium", "genre": "Horror Comedy"},
    {"title": "Vedaa", "year": 2024, "hero": "John Abraham", "heroine": "Sharvari Wagh", "difficulty": "medium", "genre": "Action"},
    {"title": "Auron Mein Kahan Dum Tha", "year": 2024, "hero": "Ajay Devgn", "heroine": "Tabu", "difficulty": "medium", "genre": "Romance"},
    {"title": "Shaitaan", "year": 2024, "hero": "Ajay Devgn", "heroine": "R Madhavan", "difficulty": "medium", "genre": "Horror"},
    {"title": "Laapataa Ladies", "year": 2024, "hero": "Sparsh Shrivastav", "heroine": "Nitanshi Goel", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Ae Watan Mere Watan", "year": 2024, "hero": "Emraan Hashmi", "heroine": "Sara Ali Khan", "difficulty": "medium", "genre": "Biography"},
    {"title": "Do Aur Do Pyaar", "year": 2024, "hero": "Vidya Balan", "heroine": "Pratik Gandhi", "difficulty": "medium", "genre": "Romance"},
    {"title": "Singham Again", "year": 2024, "hero": "Ajay Devgn", "heroine": "Kareena Kapoor", "difficulty": "medium", "genre": "Action"},
    {"title": "Bhool Bhulaiyaa 3", "year": 2024, "hero": "Kartik Aaryan", "heroine": "Triptii Dimri", "difficulty": "medium", "genre": "Horror Comedy"},
    {"title": "Khiladi", "year": 1992, "hero": "Akshay Kumar", "heroine": "Ayesha Jhulka", "difficulty": "medium", "genre": "Thriller"},
    {"title": "Andaz Apna Apna", "year": 1994, "hero": "Aamir Khan", "heroine": "Karisma Kapoor", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Raja Hindustani", "year": 1996, "hero": "Aamir Khan", "heroine": "Karisma Kapoor", "difficulty": "medium", "genre": "Romance"},
    {"title": "Akele Hum Akele Tum", "year": 1995, "hero": "Aamir Khan", "heroine": "Manisha Koirala", "difficulty": "medium", "genre": "Drama"},
    {"title": "Sarfarosh", "year": 1999, "hero": "Aamir Khan", "heroine": "Sonali Bendre", "difficulty": "medium", "genre": "Action"},
    {"title": "Zakhm", "year": 1998, "hero": "Ajay Devgn", "heroine": "Pooja Bhatt", "difficulty": "medium", "genre": "Drama"},
    {"title": "Ishq", "year": 1997, "hero": "Aamir Khan", "heroine": "Juhi Chawla", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Yes Boss", "year": 1997, "hero": "Shah Rukh Khan", "heroine": "Juhi Chawla", "difficulty": "medium", "genre": "Romance"},
    {"title": "Duplicate", "year": 1998, "hero": "Shah Rukh Khan", "heroine": "Juhi Chawla", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Koyla", "year": 1997, "hero": "Shah Rukh Khan", "heroine": "Madhuri Dixit", "difficulty": "medium", "genre": "Action"},
    {"title": "Dil Hai Ki Manta Nahin", "year": 1991, "hero": "Aamir Khan", "heroine": "Pooja Bhatt", "difficulty": "medium", "genre": "Romance"},
    {"title": "Jo Jeeta Wohi Sikandar", "year": 1992, "hero": "Aamir Khan", "heroine": "Ayesha Jhulka", "difficulty": "medium", "genre": "Sports"},
    {"title": "Phool Aur Kaante", "year": 1991, "hero": "Ajay Devgn", "heroine": "Madhoo", "difficulty": "medium", "genre": "Action"},
    {"title": "Deewana", "year": 1992, "hero": "Shah Rukh Khan", "heroine": "Divya Bharti", "difficulty": "medium", "genre": "Romance"},
    {"title": "Saajan", "year": 1991, "hero": "Sanjay Dutt", "heroine": "Madhuri Dixit", "difficulty": "medium", "genre": "Romance"},
    {"title": "Sadak", "year": 1991, "hero": "Sanjay Dutt", "heroine": "Pooja Bhatt", "difficulty": "medium", "genre": "Thriller"},
    {"title": "Aashiqui", "year": 1990, "hero": "Rahul Roy", "heroine": "Anu Agarwal", "difficulty": "medium", "genre": "Romance"},
    {"title": "Ghayal", "year": 1990, "hero": "Sunny Deol", "heroine": "Meenakshi Seshadri", "difficulty": "medium", "genre": "Action"},
    {"title": "Dil", "year": 1990, "hero": "Aamir Khan", "heroine": "Madhuri Dixit", "difficulty": "medium", "genre": "Romance"},
    {"title": "Tridev", "year": 1989, "hero": "Sunny Deol", "heroine": "Madhuri Dixit", "difficulty": "medium", "genre": "Action"},
    {"title": "Ram Lakhan", "year": 1989, "hero": "Anil Kapoor", "heroine": "Madhuri Dixit", "difficulty": "medium", "genre": "Action"},
    {"title": "Karma", "year": 1986, "hero": "Dilip Kumar", "heroine": "Nutan", "difficulty": "medium", "genre": "Action"},
    {"title": "Naam", "year": 1986, "hero": "Sanjay Dutt", "heroine": "Amrita Singh", "difficulty": "medium", "genre": "Drama"},
    {"title": "Hero", "year": 1983, "hero": "Jackie Shroff", "heroine": "Meenakshi Seshadri", "difficulty": "medium", "genre": "Action"},
    {"title": "Coolie", "year": 1983, "hero": "Amitabh Bachchan", "heroine": "Rati Agnihotri", "difficulty": "medium", "genre": "Action"},
    {"title": "Shakti", "year": 1982, "hero": "Amitabh Bachchan", "heroine": "Raakhee", "difficulty": "medium", "genre": "Action"},
    {"title": "Namak Halaal", "year": 1982, "hero": "Amitabh Bachchan", "heroine": "Smita Patil", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Satte Pe Satta", "year": 1982, "hero": "Amitabh Bachchan", "heroine": "Hema Malini", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Laawaris", "year": 1981, "hero": "Amitabh Bachchan", "heroine": "Zeenat Aman", "difficulty": "medium", "genre": "Action"},
    {"title": "Naseeb", "year": 1981, "hero": "Amitabh Bachchan", "heroine": "Hema Malini", "difficulty": "medium", "genre": "Action"},
    {"title": "Kaalia", "year": 1981, "hero": "Amitabh Bachchan", "heroine": "Parveen Babi", "difficulty": "medium", "genre": "Action"},
    {"title": "Shaan", "year": 1980, "hero": "Amitabh Bachchan", "heroine": "Parveen Babi", "difficulty": "medium", "genre": "Action"},
    {"title": "The Burning Train", "year": 1980, "hero": "Dharmendra", "heroine": "Hema Malini", "difficulty": "medium", "genre": "Thriller"},
    {"title": "Dostana", "year": 1980, "hero": "Amitabh Bachchan", "heroine": "Zeenat Aman", "difficulty": "medium", "genre": "Drama"},
    {"title": "Suhaag", "year": 1979, "hero": "Amitabh Bachchan", "heroine": "Rekha", "difficulty": "medium", "genre": "Action"},
    {"title": "Muqaddar Ka Sikandar", "year": 1978, "hero": "Amitabh Bachchan", "heroine": "Rekha", "difficulty": "medium", "genre": "Drama"},
    {"title": "Trishul", "year": 1978, "hero": "Amitabh Bachchan", "heroine": "Raakhee", "difficulty": "medium", "genre": "Drama"},
    {"title": "Kasme Vaade", "year": 1978, "hero": "Amitabh Bachchan", "heroine": "Raakhee", "difficulty": "medium", "genre": "Drama"},
    {"title": "Hera Pheri", "year": 1976, "hero": "Amitabh Bachchan", "heroine": "Saira Banu", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Kabhi Kabhie", "year": 1976, "hero": "Amitabh Bachchan", "heroine": "Raakhee", "difficulty": "medium", "genre": "Romance"},
    {"title": "Chupke Chupke", "year": 1975, "hero": "Dharmendra", "heroine": "Sharmila Tagore", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Zanjeer", "year": 1973, "hero": "Amitabh Bachchan", "heroine": "Jaya Bachchan", "difficulty": "medium", "genre": "Action"},
    {"title": "Bobby", "year": 1973, "hero": "Rishi Kapoor", "heroine": "Dimple Kapadia", "difficulty": "medium", "genre": "Romance"},
    {"title": "Yaadon Ki Baaraat", "year": 1973, "hero": "Dharmendra", "heroine": "Zeenat Aman", "difficulty": "medium", "genre": "Action"},
    {"title": "Pakeezah", "year": 1972, "hero": "Raaj Kumar", "heroine": "Meena Kumari", "difficulty": "medium", "genre": "Romance"},
    {"title": "Anand", "year": 1971, "hero": "Rajesh Khanna", "heroine": "Sumita Sanyal", "difficulty": "medium", "genre": "Drama"},
    {"title": "Mera Naam Joker", "year": 1970, "hero": "Raj Kapoor", "heroine": "Simi Garewal", "difficulty": "medium", "genre": "Drama"},
    {"title": "Aradhana", "year": 1969, "hero": "Rajesh Khanna", "heroine": "Sharmila Tagore", "difficulty": "medium", "genre": "Romance"},
    {"title": "Sachcha Jhutha", "year": 1970, "hero": "Rajesh Khanna", "heroine": "Mumtaz", "difficulty": "medium", "genre": "Comedy"},
    {"title": "Jewel Thief", "year": 1967, "hero": "Dev Anand", "heroine": "Vyjayanthimala", "difficulty": "medium", "genre": "Thriller"},
    {"title": "Guide", "year": 1965, "hero": "Dev Anand", "heroine": "Waheeda Rehman", "difficulty": "medium", "genre": "Drama"},
    {"title": "Waqt", "year": 1965, "hero": "Sunil Dutt", "heroine": "Sadhana", "difficulty": "medium", "genre": "Drama"},
    {"title": "Padosan", "year": 1968, "hero": "Sunil Dutt", "heroine": "Saira Banu", "difficulty": "medium", "genre": "Comedy"},
    
    # ==================== HARD - Obscure/Complex Titles (170+ movies) ====================
    {"title": "Jaane Bhi Do Yaaro", "year": 1983, "hero": "Naseeruddin Shah", "heroine": "Bhakti Barve", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Katha", "year": 1983, "hero": "Naseeruddin Shah", "heroine": "Deepti Naval", "difficulty": "hard", "genre": "Drama"},
    {"title": "Ardh Satya", "year": 1983, "hero": "Om Puri", "heroine": "Smita Patil", "difficulty": "hard", "genre": "Drama"},
    {"title": "Mirch Masala", "year": 1987, "hero": "Naseeruddin Shah", "heroine": "Smita Patil", "difficulty": "hard", "genre": "Drama"},
    {"title": "Ankur", "year": 1974, "hero": "Anant Nag", "heroine": "Shabana Azmi", "difficulty": "hard", "genre": "Drama"},
    {"title": "Sparsh", "year": 1980, "hero": "Naseeruddin Shah", "heroine": "Shabana Azmi", "difficulty": "hard", "genre": "Drama"},
    {"title": "Paar", "year": 1984, "hero": "Naseeruddin Shah", "heroine": "Shabana Azmi", "difficulty": "hard", "genre": "Drama"},
    {"title": "Manthan", "year": 1976, "hero": "Girish Karnad", "heroine": "Smita Patil", "difficulty": "hard", "genre": "Drama"},
    {"title": "Bhumika", "year": 1977, "hero": "Amol Palekar", "heroine": "Smita Patil", "difficulty": "hard", "genre": "Drama"},
    {"title": "Ijaazat", "year": 1987, "hero": "Naseeruddin Shah", "heroine": "Rekha", "difficulty": "hard", "genre": "Drama"},
    {"title": "Ek Duuje Ke Liye", "year": 1981, "hero": "Kamal Haasan", "heroine": "Rati Agnihotri", "difficulty": "hard", "genre": "Romance"},
    {"title": "Saaransh", "year": 1984, "hero": "Anupam Kher", "heroine": "Rohini Hattangadi", "difficulty": "hard", "genre": "Drama"},
    {"title": "Jaane Tu Ya Jaane Na", "year": 2008, "hero": "Imran Khan", "heroine": "Genelia D'Souza", "difficulty": "hard", "genre": "Romance"},
    {"title": "Band Baaja Baaraat", "year": 2010, "hero": "Ranveer Singh", "heroine": "Anushka Sharma", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Dev D", "year": 2009, "hero": "Abhay Deol", "heroine": "Mahie Gill", "difficulty": "hard", "genre": "Drama"},
    {"title": "Oye Lucky Lucky Oye", "year": 2008, "hero": "Abhay Deol", "heroine": "Paresh Rawal", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Pyaar Ke Side Effects", "year": 2006, "hero": "Rahul Bose", "heroine": "Mallika Sherawat", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Khosla Ka Ghosla", "year": 2006, "hero": "Anupam Kher", "heroine": "Boman Irani", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Johnny Gaddaar", "year": 2007, "hero": "Neil Nitin Mukesh", "heroine": "Rimi Sen", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Maqbool", "year": 2003, "hero": "Irrfan Khan", "heroine": "Tabu", "difficulty": "hard", "genre": "Crime"},
    {"title": "Gulaal", "year": 2009, "hero": "Raj Singh Chaudhary", "heroine": "Jesse Randhawa", "difficulty": "hard", "genre": "Drama"},
    {"title": "Shanghai", "year": 2012, "hero": "Emraan Hashmi", "heroine": "Kalki Koechlin", "difficulty": "hard", "genre": "Drama"},
    {"title": "Ishqiya", "year": 2010, "hero": "Naseeruddin Shah", "heroine": "Vidya Balan", "difficulty": "hard", "genre": "Crime"},
    {"title": "Dedh Ishqiya", "year": 2014, "hero": "Naseeruddin Shah", "heroine": "Madhuri Dixit", "difficulty": "hard", "genre": "Crime"},
    {"title": "Aligarh", "year": 2015, "hero": "Manoj Bajpayee", "heroine": "Rajkummar Rao", "difficulty": "hard", "genre": "Drama"},
    {"title": "A Death in the Gunj", "year": 2016, "hero": "Vikrant Massey", "heroine": "Kalki Koechlin", "difficulty": "hard", "genre": "Drama"},
    {"title": "Mukti Bhawan", "year": 2016, "hero": "Adil Hussain", "heroine": "Lalit Behl", "difficulty": "hard", "genre": "Drama"},
    {"title": "Photograph", "year": 2019, "hero": "Nawazuddin Siddiqui", "heroine": "Sanya Malhotra", "difficulty": "hard", "genre": "Romance"},
    {"title": "Thappad", "year": 2020, "hero": "Pavail Gulati", "heroine": "Taapsee Pannu", "difficulty": "hard", "genre": "Drama"},
    {"title": "Bulbbul", "year": 2020, "hero": "Avinash Tiwary", "heroine": "Tripti Dimri", "difficulty": "hard", "genre": "Horror"},
    {"title": "Pagglait", "year": 2021, "hero": "Ashutosh Rana", "heroine": "Sanya Malhotra", "difficulty": "hard", "genre": "Drama"},
    {"title": "Raat Akeli Hai", "year": 2020, "hero": "Nawazuddin Siddiqui", "heroine": "Radhika Apte", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Ludo", "year": 2020, "hero": "Abhishek Bachchan", "heroine": "Rajkummar Rao", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Mimi", "year": 2021, "hero": "Pankaj Tripathi", "heroine": "Kriti Sanon", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Sardar Udham", "year": 2021, "hero": "Vicky Kaushal", "heroine": "Banita Sandhu", "difficulty": "hard", "genre": "Drama"},
    {"title": "Haseen Dillruba", "year": 2021, "hero": "Vikrant Massey", "heroine": "Taapsee Pannu", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Tribhanga", "year": 2021, "hero": "Mithila Palkar", "heroine": "Kajol", "difficulty": "hard", "genre": "Drama"},
    {"title": "Dhamaka", "year": 2021, "hero": "Kartik Aaryan", "heroine": "Mrunal Thakur", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Jalsa", "year": 2022, "hero": "Shefali Shah", "heroine": "Vidya Balan", "difficulty": "hard", "genre": "Drama"},
    {"title": "Gehraiyaan", "year": 2022, "hero": "Siddhant Chaturvedi", "heroine": "Deepika Padukone", "difficulty": "hard", "genre": "Romance"},
    {"title": "Badhaai Do", "year": 2022, "hero": "Rajkummar Rao", "heroine": "Bhumi Pednekar", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Jhund", "year": 2022, "hero": "Amitabh Bachchan", "heroine": "Rinku Rajguru", "difficulty": "hard", "genre": "Sports"},
    {"title": "Monica O My Darling", "year": 2022, "hero": "Rajkummar Rao", "heroine": "Huma Qureshi", "difficulty": "hard", "genre": "Thriller"},
    {"title": "An Action Hero", "year": 2022, "hero": "Ayushmann Khurrana", "heroine": "Malaika Arora", "difficulty": "hard", "genre": "Action"},
    {"title": "Freddy", "year": 2022, "hero": "Kartik Aaryan", "heroine": "Alaya F", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Drishyam 2", "year": 2022, "hero": "Ajay Devgn", "heroine": "Shriya Saran", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Qala", "year": 2022, "hero": "Babil Khan", "heroine": "Tripti Dimri", "difficulty": "hard", "genre": "Musical"},
    {"title": "Cuttputlli", "year": 2022, "hero": "Akshay Kumar", "heroine": "Rakul Preet Singh", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Doctor G", "year": 2022, "hero": "Ayushmann Khurrana", "heroine": "Rakul Preet Singh", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Goodbye", "year": 2022, "hero": "Amitabh Bachchan", "heroine": "Rashmika Mandanna", "difficulty": "hard", "genre": "Drama"},
    {"title": "Gaslight", "year": 2023, "hero": "Chitrangada Singh", "heroine": "Sara Ali Khan", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Selfiee", "year": 2023, "hero": "Akshay Kumar", "heroine": "Diana Penty", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Kacchey Limbu", "year": 2023, "hero": "Radhika Madan", "heroine": "Ayush Mehra", "difficulty": "hard", "genre": "Drama"},
    {"title": "Sirf Ek Bandaa Kaafi Hai", "year": 2023, "hero": "Manoj Bajpayee", "heroine": "Adrija Sinha", "difficulty": "hard", "genre": "Drama"},
    {"title": "Bloody Daddy", "year": 2023, "hero": "Shahid Kapoor", "heroine": "Diana Penty", "difficulty": "hard", "genre": "Action"},
    {"title": "OMG 2", "year": 2023, "hero": "Akshay Kumar", "heroine": "Pankaj Tripathi", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Dream Girl 2", "year": 2023, "hero": "Ayushmann Khurrana", "heroine": "Ananya Panday", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Fukrey 3", "year": 2023, "hero": "Pulkit Samrat", "heroine": "Richa Chadha", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Yaariyan 2", "year": 2023, "hero": "Divya Khosla Kumar", "heroine": "Meezaan Jafri", "difficulty": "hard", "genre": "Romance"},
    {"title": "The Archies", "year": 2023, "hero": "Agastya Nanda", "heroine": "Suhana Khan", "difficulty": "hard", "genre": "Musical"},
    {"title": "Salaam Venky", "year": 2022, "hero": "Kajol", "heroine": "Vishal Jethwa", "difficulty": "hard", "genre": "Drama"},
    {"title": "Anek", "year": 2022, "hero": "Ayushmann Khurrana", "heroine": "Andrea Kevichusa", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Runway 34", "year": 2022, "hero": "Ajay Devgn", "heroine": "Rakul Preet Singh", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Attack", "year": 2022, "hero": "John Abraham", "heroine": "Jacqueline Fernandez", "difficulty": "hard", "genre": "Sci-Fi"},
    {"title": "Bachchhan Paandey", "year": 2022, "hero": "Akshay Kumar", "heroine": "Kriti Sanon", "difficulty": "hard", "genre": "Action"},
    {"title": "Jayeshbhai Jordaar", "year": 2022, "hero": "Ranveer Singh", "heroine": "Shalini Pandey", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Heropanti 2", "year": 2022, "hero": "Tiger Shroff", "heroine": "Tara Sutaria", "difficulty": "hard", "genre": "Action"},
    {"title": "Jersey", "year": 2022, "hero": "Shahid Kapoor", "heroine": "Mrunal Thakur", "difficulty": "hard", "genre": "Sports"},
    {"title": "Samrat Prithviraj", "year": 2022, "hero": "Akshay Kumar", "heroine": "Manushi Chhillar", "difficulty": "hard", "genre": "Historical"},
    {"title": "Khuda Haafiz 2", "year": 2022, "hero": "Vidyut Jammwal", "heroine": "Shivaleeka Oberoi", "difficulty": "hard", "genre": "Action"},
    {"title": "Rashtra Kavach Om", "year": 2022, "hero": "Aditya Roy Kapur", "heroine": "Sanjana Sanghi", "difficulty": "hard", "genre": "Action"},
    {"title": "Hit The First Case", "year": 2022, "hero": "Rajkummar Rao", "heroine": "Sanya Malhotra", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Shamshera", "year": 2022, "hero": "Ranbir Kapoor", "heroine": "Vaani Kapoor", "difficulty": "hard", "genre": "Action"},
    {"title": "Ek Villain Returns", "year": 2022, "hero": "John Abraham", "heroine": "Disha Patani", "difficulty": "hard", "genre": "Action"},
    {"title": "Liger", "year": 2022, "hero": "Vijay Deverakonda", "heroine": "Ananya Panday", "difficulty": "hard", "genre": "Sports"},
    {"title": "Dobaaraa", "year": 2022, "hero": "Taapsee Pannu", "heroine": "Pavail Gulati", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Raksha Bandhan", "year": 2022, "hero": "Akshay Kumar", "heroine": "Bhumi Pednekar", "difficulty": "hard", "genre": "Drama"},
    {"title": "Thank God", "year": 2022, "hero": "Ajay Devgn", "heroine": "Sidharth Malhotra", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Ram Setu", "year": 2022, "hero": "Akshay Kumar", "heroine": "Jacqueline Fernandez", "difficulty": "hard", "genre": "Adventure"},
    {"title": "Phone Bhoot", "year": 2022, "hero": "Siddhant Chaturvedi", "heroine": "Katrina Kaif", "difficulty": "hard", "genre": "Horror Comedy"},
    {"title": "Uunchai", "year": 2022, "hero": "Amitabh Bachchan", "heroine": "Boman Irani", "difficulty": "hard", "genre": "Drama"},
    {"title": "Bhediya", "year": 2022, "hero": "Varun Dhawan", "heroine": "Kriti Sanon", "difficulty": "hard", "genre": "Horror Comedy"},
    {"title": "Vikram Vedha", "year": 2022, "hero": "Hrithik Roshan", "heroine": "Saif Ali Khan", "difficulty": "hard", "genre": "Action"},
    {"title": "Maarrich", "year": 2022, "hero": "Tusshar Kapoor", "heroine": "Naseeruddin Shah", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Atrangi Re", "year": 2021, "hero": "Akshay Kumar", "heroine": "Sara Ali Khan", "difficulty": "hard", "genre": "Romance"},
    {"title": "Chandigarh Kare Aashiqui", "year": 2021, "hero": "Ayushmann Khurrana", "heroine": "Vaani Kapoor", "difficulty": "hard", "genre": "Romance"},
    {"title": "Tadap", "year": 2021, "hero": "Ahan Shetty", "heroine": "Tara Sutaria", "difficulty": "hard", "genre": "Action"},
    {"title": "Antim", "year": 2021, "hero": "Salman Khan", "heroine": "Aayush Sharma", "difficulty": "hard", "genre": "Action"},
    {"title": "Bunty Aur Babli 2", "year": 2021, "hero": "Saif Ali Khan", "heroine": "Rani Mukerji", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Meenakshi Sundareshwar", "year": 2021, "hero": "Sanya Malhotra", "heroine": "Abhimanyu Dassani", "difficulty": "hard", "genre": "Romance"},
    {"title": "Hum Do Hamare Do", "year": 2021, "hero": "Rajkummar Rao", "heroine": "Kriti Sanon", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Bhavai", "year": 2021, "hero": "Pratik Gandhi", "heroine": "Aindrita Ray", "difficulty": "hard", "genre": "Drama"},
    {"title": "Rashmi Rocket", "year": 2021, "hero": "Abhishek Banerjee", "heroine": "Taapsee Pannu", "difficulty": "hard", "genre": "Sports"},
    {"title": "Bhuj The Pride of India", "year": 2021, "hero": "Ajay Devgn", "heroine": "Sonakshi Sinha", "difficulty": "hard", "genre": "War"},
    {"title": "Radhe", "year": 2021, "hero": "Salman Khan", "heroine": "Disha Patani", "difficulty": "hard", "genre": "Action"},
    {"title": "Toofaan", "year": 2021, "hero": "Farhan Akhtar", "heroine": "Mrunal Thakur", "difficulty": "hard", "genre": "Sports"},
    {"title": "Chehre", "year": 2021, "hero": "Amitabh Bachchan", "heroine": "Emraan Hashmi", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Hungama 2", "year": 2021, "hero": "Shilpa Shetty", "heroine": "Meezaan Jafri", "difficulty": "hard", "genre": "Comedy"},
    {"title": "Satyameva Jayate 2", "year": 2021, "hero": "John Abraham", "heroine": "Divya Khosla Kumar", "difficulty": "hard", "genre": "Action"},
    {"title": "Sanak", "year": 2021, "hero": "Vidyut Jammwal", "heroine": "Neha Dhupia", "difficulty": "hard", "genre": "Action"},
    {"title": "Sandeep Aur Pinky Faraar", "year": 2021, "hero": "Arjun Kapoor", "heroine": "Parineeti Chopra", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Mumbai Saga", "year": 2021, "hero": "John Abraham", "heroine": "Emraan Hashmi", "difficulty": "hard", "genre": "Crime"},
    {"title": "Roohi", "year": 2021, "hero": "Rajkummar Rao", "heroine": "Janhvi Kapoor", "difficulty": "hard", "genre": "Horror Comedy"},
    {"title": "The White Tiger", "year": 2021, "hero": "Adarsh Gourav", "heroine": "Priyanka Chopra", "difficulty": "hard", "genre": "Drama"},
    {"title": "Saina", "year": 2021, "hero": "Parineeti Chopra", "heroine": "Manav Kaul", "difficulty": "hard", "genre": "Sports"},
    {"title": "Thalaivii", "year": 2021, "hero": "Kangana Ranaut", "heroine": "Arvind Swami", "difficulty": "hard", "genre": "Biography"},
    {"title": "Bob Biswas", "year": 2021, "hero": "Abhishek Bachchan", "heroine": "Chitrangada Singh", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Ajeeb Daastaans", "year": 2021, "hero": "Fatima Sana Shaikh", "heroine": "Jaideep Ahlawat", "difficulty": "hard", "genre": "Drama"},
    {"title": "AK vs AK", "year": 2020, "hero": "Anil Kapoor", "heroine": "Anurag Kashyap", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Gunjan Saxena", "year": 2020, "hero": "Janhvi Kapoor", "heroine": "Pankaj Tripathi", "difficulty": "hard", "genre": "Biography"},
    {"title": "Dil Bechara", "year": 2020, "hero": "Sushant Singh Rajput", "heroine": "Sanjana Sanghi", "difficulty": "hard", "genre": "Romance"},
    {"title": "Shakuntala Devi", "year": 2020, "hero": "Vidya Balan", "heroine": "Sanya Malhotra", "difficulty": "hard", "genre": "Biography"},
    {"title": "Khaali Peeli", "year": 2020, "hero": "Ishaan Khatter", "heroine": "Ananya Panday", "difficulty": "hard", "genre": "Action"},
    {"title": "Laxmii", "year": 2020, "hero": "Akshay Kumar", "heroine": "Kiara Advani", "difficulty": "hard", "genre": "Horror"},
    {"title": "Sadak 2", "year": 2020, "hero": "Sanjay Dutt", "heroine": "Alia Bhatt", "difficulty": "hard", "genre": "Thriller"},
    {"title": "Maska", "year": 2020, "hero": "Prit Kamani", "heroine": "Shirley Setia", "difficulty": "hard", "genre": "Drama"},
    {"title": "Cargo", "year": 2020, "hero": "Vikrant Massey", "heroine": "Shweta Tripathi", "difficulty": "hard", "genre": "Sci-Fi"},
    {"title": "Ginny Weds Sunny", "year": 2020, "hero": "Yami Gautam", "heroine": "Vikrant Massey", "difficulty": "hard", "genre": "Romance"},
    {"title": "Dolly Kitty Aur Woh Chamakte Sitare", "year": 2020, "hero": "Konkona Sen Sharma", "heroine": "Bhumi Pednekar", "difficulty": "hard", "genre": "Drama"},
]
